.TH "NativeDisplayManager::MonitorInfo" 3 "Version 1.0" "NativeDisplayManager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NativeDisplayManager::MonitorInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "unsigned int \fBwidth\fP"
.br
.ti -1c
.RI "unsigned int \fBheight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBmonitor\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned int NativeDisplayManager::MonitorInfo::height"

.PP
Definition at line \fB19\fP of file \fBmonitor\&.hpp\fP\&.
.SS "std::string NativeDisplayManager::MonitorInfo::name"

.PP
Definition at line \fB17\fP of file \fBmonitor\&.hpp\fP\&.
.SS "unsigned int NativeDisplayManager::MonitorInfo::width"

.PP
Definition at line \fB18\fP of file \fBmonitor\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NativeDisplayManager from the source code\&.
